### PR TITLE
Use Loggly Bulk Endpoint for multiple messages.

### PR DESCRIPTION
**Pull request by adamhathcock**
We had problems sending a lot of messages so using the bulk endpoint is a requirement for me.

Added new IEnumerable overload to ILogglyClient.
All code expects an IEnumerable.
Made most things async/await.
Tested Bulk endpoint
Syslog endpoints are untested but not much changed there.

If this looks good, I'd probably want to change to use HttpClient and persist the client to leave connections open longer for better performance.

### CODE REVIEW

**Comment by neutmute** [comment]
Hi Adam - thank you for the PR!
Have you dogfooded the change? I'm not using loggly on my current projects.

**Comment by adamhathcock** [comment]
I have tested the Http transport with my codebase and the bulk endpoint.  We haven't pushed into the codebase yet because we were going to see if this was going to be accepted or we needed to fork internally :)

**Comment by neutmute** [comment]
I'm pretty busy on a new project so I don't have time to test this myself but it all looks good. 
How about I merge and publish as a prerelease nuget package, you dogfood it a bit more and then I'll publish the full package?

**Comment by adamhathcock** [comment]
Sounds like a good compromise.  I might also use HttpClient for long-lived connections in another pull request later.

**Comment by neutmute** [comment]
prerelease published
https://www.nuget.org/packages/loggly-csharp/4.5.0.4-beta1

**Pull request merged**
