### PR TITLE
Don't use Task.Run as we're now "async all the way"

### PR DESCRIPTION
**Pull request by adamhathcock**
This is really just a minor change.  The bulk insertion code seems to be working happily for me.

### CODE REVIEW

**Comment by neutmute** [comment]
hmm - doesn't this change the contract for consumers that don't upgrade in sync? 
For example last year I broke the serilog adapter for this with a similar change when the adapter dependency pulled the latest package but the adapter itself had been compiled against the prior contract

**Comment by adamhathcock** [comment]
The contract doesn't change.  Before you were running a new Task on an synchronous thread of execution.  Now that I exposed the async methods all the way to the top as a part of the Task, you don't need Task.Run anymore.  The signature of the method is the same and the Task object returned is still managing the async execution.  It just happens with async/await now and all the goodness that provides.

I'm actually using the serilog adapter with this and it all works.  I'd have to see what you changed before to understand why this is possibly different this time.

**Comment by neutmute** [comment]
ok cool

**Comment by neutmute** [comment]
published as 4.5.0.4!
https://www.nuget.org/packages/loggly-csharp/

**Comment by adamhathcock** [comment]
Thanks!

**Pull request merged**
