### PR TITLE
Upgrade AppVeyor to VS2019

### PR DESCRIPTION
**Pull request by snakefoot**

### CODE REVIEW

**Comment by neutmute** [comment]
love your work!

**Comment by snakefoot** [comment]
Now there is a succesful build, but the nuget-api-key is causing issues:

```
Publishing Loggly.4.6.1.100.nupkg to https://www.nuget.org/api/v2/package...
Error publishing package. NuGet server returned 403: The specified API key is invalid, has expired, or does not have permission to access the specified package.
```

https://ci.appveyor.com/project/neutmute/loggly-csharp/builds/39161501

**Comment by neutmute** [comment]
yep sorry - been distracted and not entirely sure why that api key isn't
working. will try and crack it over the weekend

**Comment by neutmute** [comment]
well that was confusing but fixed now. build was producing packages but the wrong name. So the `specified API key is invalid` was not because my key was wrong but because appveyor was trying to publish packages owned by someone else.

**Comment by snakefoot** [comment]
Oops. That was my mistake.

**Pull request merged**
