### PR TITLE
Allowing for the LogglyClient to take a customer token as a parameter

### PR DESCRIPTION
**Pull request by bkrauska**
This is for Issue #35

### CODE REVIEW

**Comment by neutmute** [comment]
thank you for the contribution! I'll take a closer look over the next day or so

**Comment by neutmute** [comment]
Just taking a look at this - not sure it really solves #35 since that scenario was multiple customer keys in the one app domain (as I read it). 

The new constructor still takes the customer token and places it in the static config instance: {{LogglyConfig.Instance.CustomerToken = customerToken;}}
So if you have multiple threads creating loggly clients with different tokens, it will be pot luck which customerToken any log gets sent to.

Was it your intent to solve that problem or does this PR scratch a different itch?

**Comment by bkrauska** [comment]
Oh, I guess I misread the issue they were having. This PR addresses a different issue we having through our deployment system. Allow for the key to be set by the user allows for Azure Cloud Service Configs or normal AppSettings to be used directly between environmental changes without recompiles and/or environment specific transforms.

**Comment by neutmute** [comment]
OK so the real requirement is to be able to programmatically set the config and not use the custom app.config section?
That should already work though - just by manipulating the static config directly no?

`LogglyConfig.Instance.CustomerToken = "your customer token here";`

**Comment by bkrauska** [comment]
I'll have to give that a try. I thought I was getting a config error when you don't have the customer token in that section.

**Comment by neutmute** [comment]
Yes, give it a try I think it should work. If you read the `LogglyConfig.Instance`, it will try and read app config but if it is missing will create a new empty config for you to populate programatically.

It will blow up if you try to log without a customer token set so I guess you need to do the setup very early in the application lifecycle before any logs start.

Let me know how you go!

**Comment by neutmute** [comment]
I tested config via code only in an ASP.NET Core app and it works fine as is - will close this PR as not required. 

readme.md updated:

```
    var config = LogglyConfig.Instance;
    config.CustomerToken = "1ceb00da-cec7-45cb-8135-d3adbeef";
    config.ApplicationName = $"MyApp-{_environmentName}";

    config.Transport.EndpointHostname = "logs-01.loggly.com";
    config.Transport.EndpointPort = 443;
    config.Transport.LogTransport = LogTransport.Https;

    var ct = new ApplicationNameTag();
    ct.Formatter = "application-{0}";
    config.TagConfig.Tags.Add(ct);
```

**Pull request closed without merging**
